name: Run RSpec
on:
  workflow_call:
    inputs:
      # This tells the build which library to run
      library:
        required: true
        type: string

      # This tells rspec-rails what branch to run in ci it is passed in to allow the @main
      # version of this workflow to be shared amongst branches
      rspec_version:
        required: true
        type: string

permissions:
  contents: read

env:
  DIFF_LCS_VERSION: "> 1.4.3"
  RSPEC_CI: true
  RSPEC_VERSION: ${{ inputs.rspec_version }}

jobs:
  rspec:
    name: Ruby ${{ matrix.ruby }} ${{ matrix.name_extra || '' }}
    runs-on: ${{ matrix.os || 'ubuntu-20.04' }}
    strategy:
      matrix:
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - 2.7
          - 2.6
          - 2.5
          - 2.4
          - 2.3
          - 2.2
      fail-fast: false
    continue-on-error: ${{ matrix.allow_failure || endsWith(matrix.ruby, 'head') }}
    defaults:
      run:
        working-directory: ${{ inputs.library }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: ../script/update_rubygems_and_install_bundler
      - run: bundle install --standalone
      - run: bundle binstubs --all
      - run: ../script/run_rspec
      - run: ../script/run_rspec_one_by_one
      - run: ../script/run_cucumber
